#!/bin/bash

###########################################################
#BEGIN SCRIPT VARIABLES
###########################################################

#Define the current branch.
export OLCAO_BRANCH="olcao"

#Root directories of the OLCAO program suite and any additional codes.
if [ -z ${1+foo} ]; then
   export OLCAO_DIR="$HOME/$OLCAO_BRANCH" # Default
else
   export OLCAO_DIR="$1" # Command line provided (used by nanoHUB)
fi
export GRASP2K_DIR="$OLCAO_DIR/src/grasp2k/grasp2Kdev"

#Default location of all script resource control files.
export OLCAO_RC="$OLCAO_DIR/.olcao"

#Location of binary executables.
export OLCAO_BIN="$OLCAO_DIR/bin"
export GRASP2K_BIN="$GRASP2K_DIR/bin"

#Location of data files.
export OLCAO_DATA="$OLCAO_DIR/share"

#Location for all intermediate directories.
if [ -z ${1+foo} ]; then
   export OLCAO_TEMP="$HOME/data/scratch/$OLCAO_BRANCH" # Default
else
   export OLCAO_TEMP="/tmp" # Command line provided (used by nanoHUB)
fi

#Execution mechanism for Fortran programs within the olcao script.
#export OLCAO_EXE="srun -n1 --exclusive"
export OLCAO_EXE=""

#Modifications of the linux environment.
export PATH=$OLCAO_BIN:$PATH
export PERL5LIB=$OLCAO_BIN/perl5:$PERL5LIB

#Type of tar tool available:  Valid values are "linux" or "unix".
export OLCAO_TAR="linux"

#Do intermediate files need to be touched?  Yes=1, No=0
export OLCAO_TOUCH=0

#Number of bytes for FORTRAN 90 floating point doubles.
#This is needed for memory estimation.
export OLCAO_DOUBLE=16

#Define the type of queueing system used on this machine.
# 0 = BASH SCRIPT; 1 = PBS; 2 = LSF; 3 = SLURM;
export OLCAO_QUEUE=3

#Define the head location of the VASP pseudopotential database.
export VASPPOT_DIR="/cluster/VAST/rulisp-lab/cpg/vasp_pot"

# Define the location of each type of VASP potential.
export VASPPOT_USPP_LDA="$VASPPOT_DIR/potUSPP_LDA"
export VASPPOT_USPP_GGA="$VASPPOT_DIR/potUSPP_GGA"
export VASPPOT_PAW_LDA="$VASPPOT_DIR/potpaw_LDA"
export VASPPOT_PAW_GGA="$VASPPOT_DIR/potpaw_GGA"
export VASPPOT_PAW_PBE="$VASPPOT_DIR/potpaw_PBE"
export VASPPOT_PAW_LDA5x="$VASPPOT_DIR/potpaw_LDA.52"
export VASPPOT_PAW_PBE5x="$VASPPOT_DIR/potpaw_PBE.52"

###########################################################
#END SCRIPT VARIABLES
###########################################################
