#!/usr/bin/env perl
#This script will take a single argument.
#The argument must be a directory (either exact or relative reference).  Then
#this script will make a directory hierarchy if the given directories do not
#already exist.

$directory=$ARGV[0];
@values=split(/\//,"$directory");

if ($values[0] eq "")
{
   $directory="";
   for ($i=1;$i<=$#values;$i++)
   {
      $directory = "$directory"."/"."$values[$i]";
      if (! -d "$directory")
         {system("mkdir $directory");}
   }
}
else
{
   $directory="";
   for ($i=0;$i<=$#values;$i++)
   {
      $directory = "$directory"."$values[$i]"."/";
      if (! -d "$directory")
         {system("mkdir $directory");}
   }
}
