#!/usr/bin/env perl
sub printHelp
{
   print STDOUT <<ENDHELP;
###############################################################################
#Program:  pdb2skl
#Purpose:  This program will convert a protien data bank .pdb file into an
#          olcao.skl input file with the atoms all rearranged such that they
#          are sorted according to their elements.  This will also produce a
#          mapping between the pdb file atoms and the skl atoms.
#
#USAGE:  pdb2skl [-i \$pdbInputFile] [-o \$sklOutputFile] [-m \$mapFile]
#                 [-pdbtypes] [-help]
#
#The -i option is used to request that a specific input file be used for the
#   conversion.  If this option is not given, then the default value for the
#   input file is model.pdb.
#The -o option is used to request that a specific output file be written to
#   for the conversion.  If this option is not given, then the default value
#   for the output file is skl.dat.
#The -m option is used to request that the mapping between the pdb and skl
#   files be stored in the file named \$mapFile.
#The -pdbtypes option will require that the skl.dat file use the types as
#   defined in the pdb file.  The default is to have no types assigned.
#   
###############################################################################
ENDHELP
   exit;
}

# BEGIN PROGRAM EXECUTION #################

# Use necessary modules.
use strict;
use warnings;
use Env;
use lib "$OLCAO_BIN/perl5";
use ElementData;
use StructureControl;

# Declare global variables.
my $pdbTypes;
my $pdbFile;
my $sklFile;
my $mapFile;

# Set default values for various file names.
&setDefaults;

# Read the command line for requested options.
&parseCommandLine;

# Open output files for writing.
&initEnvironment;

# Read the PDB input file and store/calculate all the important information.
StructureControl::readInputFile($pdbFile,$pdbTypes);

# Print the skl input file.
StructureControl::printOLCAO(\*SKL,"Generated from PDB file.","cartesian");

# Print the data file that maps the pdb nature of each atom to the skl atoms.
StructureControl::printOLCAOMap(\*MAP);

# END PROGRAM EXECUTION ###################

sub setDefaults
{
   # Define the default file names.
   $pdbFile  = "model.pdb";
   $sklFile  = "olcao.skl";
   $mapFile  = "skl2PDB.map";

   # Assign default behavior for types assignment.
   $pdbTypes = 0;
}

sub parseCommandLine
{
   # Define local variables.
   my $number=0;
   my $argument;
   my $commandLine = "command";

   while ($number < scalar(@ARGV))
   {
      if ($ARGV[$number] eq "-i")
      {
         $pdbFile = $ARGV[$number+1];
         $number++;
      }
      elsif ($ARGV[$number] eq "-o")
      {
         $sklFile = $ARGV[$number+1];
         $number++;
      }
      elsif ($ARGV[$number] eq "-m")
      {
         $mapFile = $ARGV[$number+1];
         $number++;
      }
      elsif ($ARGV[$number] eq "-pdbtypes")
         {$pdbTypes = 1;}
      elsif ($ARGV[$number] eq "-help")
         {&printHelp;}
      else
         {die "Unknown command line parameter.  Aborting\n";}

      $number++;
   }

   #Record the command line used to create this set of input files.
   open (COMMANDLINE,">>$commandLine");
   print COMMANDLINE "pdb2skl ";
   foreach $argument (0..$#ARGV)
      {print COMMANDLINE "$ARGV[$argument] ";}
   print COMMANDLINE "\n";
   close (COMMANDLINE);
}

sub initEnvironment
{
   # Open all files for writing.
   open (SKL,">$sklFile") || die "Cannot open $sklFile for writing.\n";
   open (MAP,">$mapFile") || die "Cannot open $mapFile for writing.\n";
}
