#!/bin/bash
#SBATCH -p Lewis
#SBATCH -J test-34c
#SBATCH -o test-34c.o%J
#SBATCH -e test-34c.e%J
#SBATCH -n 1
#SBATCH -t 00:60:00
#SBATCH --mem=10G
#
source /home/prulis/CPG/cpg-repo/v34/.olcao
export OMP_NUM_THREADS=1
cd /home/prulis/jobs/bn/bn-c/test-34c
$OLCAO_BIN/olcao -dos
$OLCAO_BIN/olcao -bond
$OLCAO_BIN/olcao -sybd
$OLCAO_BIN/olcao -optc
