#!/bin/sh

#
# standard tool
#
#middlewareDirectory=$(readlink -f $(dirname $0))
#toolDirectory=$(realpath ${middlewareDirectory}/..)
source ../.olcao/olcaorc

/usr/bin/invoke_app "$@" -t olcao \
                         -C rappture
